# Generated by Django 4.0.2 on 2022-02-14 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Registrado'), (2, 'Pagado'), (4, 'En preparación'), (6, 'En camino'), (8, 'Entregado'), (9, 'Cancelado')], default=1)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('payed', models.BooleanField(default=False)),
                ('payment_card', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('req_bill', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='internal.direction')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internal.paymentmethod')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Registrado'), (2, 'Pagado'), (4, 'En preparación'), (6, 'En camino'), (8, 'Entregado'), (9, 'Cancelado')], default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='client.order')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail', to='client.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internal.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
