# Generated by Django 4.0.2 on 2022-02-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('second_last_name', models.CharField(blank=True, default='', max_length=150)),
                ('doc_type', models.PositiveSmallIntegerField(choices=[(1, 'DNI'), (2, 'Pasaporte')])),
                ('doc_number', models.CharField(blank=True, default='', max_length=15)),
                ('birthdate', models.DateField(blank=True, default=None, null=True)),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'delivery'), (3, 'client')], default=3)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
    ]
