# Generated by Django 4.0.2 on 2022-02-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_doc_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joined',
            new_name='date_joined',
        ),
    ]
