# Generated by Django 4.0.2 on 2022-03-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_direction_alter_order_direction'),
        ('internal', '0002_alter_category_name_alter_category_upper_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direction',
        ),
    ]
